stages:
  prepare:
    cmd: python src/data.py --total_train_images ${prepare.total_train_images} --total_valid_images
      ${prepare.total_valid_images} --total_test_images ${prepare.total_test_images}
      --random_state ${prepare.random_state}
    deps:
    - data/raw/Testing
    - data/raw/Training
    - src/data.py
    - params.yaml
    params:
    - prepare.random_state
    - prepare.total_test_images
    - prepare.total_train_images
    - prepare.total_valid_images
    outs:
    - data/processed/Testing
    - data/processed/Training
    - data/processed/Validation
  train:
    deps:
    - src/train.py
    - data/processed/Testing
    - data/processed/Training
    - params.yaml
    cmd: python src/train.py --random_state ${train.random_state} --epochs ${train.epochs}
    params:
    - train.random_state
    - train.epochs
    outs:
    - models/model
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/Validation
    - src/evaluate.py
    - models/model
