name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set Environment Variables
      run: |
        echo "BASE_FILEPATH=${{ secrets.BASE_FILEPATH }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        MODEL_RUN_ID: ${{ secrets.MODEL_RUN_ID }}
      run: |
        pytest tests/test_model.py
